//
// Created by edems on 2018.10.24..
//

#ifndef OPENCV_OPENGL_AR_TOWERDEFENSE_TOWERDEFENSE_H
#define OPENCV_OPENGL_AR_TOWERDEFENSE_TOWERDEFENSE_H


class TowerDefense {

};


#endif //OPENCV_OPENGL_AR_TOWERDEFENSE_TOWERDEFENSE_H
